### ISSUE TITLE
Broken preview image in Scheduler Extra

### ISSUE THREAD

**Issue by mazuhl** [modmore/Scheduler#12]
Just a quick note to say the screenshot/preview image that shows up in the MODx Installer is missing.

![error-missing-screenshot](https://cloud.githubusercontent.com/assets/33357/5897168/bfb1237a-a538-11e4-8d2d-cbc42b9fdede.png)

**Comment by Mark-H** [comment]
Thanks @mazuhl, fixed (and also for a couple of other packages that didn't have one :P)
