### ISSUE TITLE
Recurring Tasks

### ISSUE THREAD

**Issue by Mark-H** [modmore/Scheduler#2]
Ability to specify a recurring task:
- first run date/time
- how often to run it after the first time (X hourly, daily, weekly, monthly) 
- last run or number of runs

**Comment by Mikaro** [comment]
I'm trying to reschedule the task...
http://forums.modx.com/thread/96961/scheduler---schedule-a-run-conditional#dis-post-524629
Can you give me some advice?

**Comment by Mark-H** [comment]
I don't think this will be added. The recurring scheduling works fine, though I do recommend doing it **at the start** of your task; if it encounters an error further down that makes sure it doesn't end the cycle.
