### ISSUE TITLE
[Feature] Create a run button in the CMP for each task.

### ISSUE THREAD

**Issue by Jako** [modmore/Scheduler#23]
That way i.e. a customer could run the task without knowing the assets/components/scheduler/run.php url for test purposes.

**Comment by Mark-H** [comment]
Assuming the site has cron jobs setup for scheduler, they can just by adding another run, can't they?

**Comment by Jako** [comment]
Huh, my customer is able to upload a .csv file and could click a button. I don't think that he could add another run to a cronjob. During a test phase it would have been nice to run a task with a button.

I will prepare a Quickstart Button for a 'force' reload now.

**Comment by Mark-H** [comment]
They wouldn't need to edit the cron jobs, they just need to add a run to the scheduler cmp. 

The run.php should already be executed every minute from your cron job. You're not triggering run.php manually for every run are you?

**Comment by Jako** [comment]
At the moment there is no cronjob set. I thought is is nicer to do this later, if the page goes life. I will create one now.

But one thing is missing then: A button for setting the date/time of the next run to 'now'.
